---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iam-policy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iam-policy-controller
subjects:
- kind: ServiceAccount
  name: iam-policy-controller
  namespace: open-cluster-management-agent-addon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-policy-controller
