apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iam-policy-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - list
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - iampolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - iampolicies/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
