resources:
  - policy.open-cluster-management.io_iampolicies.yaml

# Use patches to add field validation that Kubebuilder markers can't
patches:
  - path: patches.json
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: iampolicies.policy.open-cluster-management.io
